# ver http://about.travis-ci.org/docs/user/languages/php/ para más sugerencias
idioma : php

# enumere cualquier versión de PHP con la que desee probar
php :
  # utilizando alias de versiones principales

  # alias a 5.2.17
  - 5.2
  # alias a 5.3.29
  - 5.3
  # alias a una versión 5.4.x reciente
  - 5.4
  # alias a una versión 5.5.x reciente
  - 5.5
  # alias a una versión 5.6.x reciente
  - 5.6
  # alias a una versión 7.x reciente
  - 7.0
  # alias a una versión hhvm reciente
  - hhvm

# opcionalmente, especifique una lista de entornos, por ejemplo, para probar diferentes RDBMS
env :
  - DB = mysql
  - DB = pgsql

# opcionalmente configurar exclusiones y fallas permitidas en la matriz
matriz :
  excluir :
    - php : hhvm
      env : DB = sql   
  allow_failures :
    - php : 7.0
    - php : hhvm


# omitiendo "script:" por defecto será phpunit
# usa la variable $ DB env para determinar el phpunit.xml a usar
script : phpunit --configuration phpunit_ $ DB.xml --coverage-text

# configurar notificaciones (correo electrónico, IRC, fogata, etc.)
notificaciones :
  irc : "  "